// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOhaA9OyTaywxinCsnKKpTTvRngWHdcQ',
    appId: '1:631796041141:web:6b858729cfacb45ed485fc',
    messagingSenderId: '631796041141',
    projectId: 'project-9eb79',
    authDomain: 'project-9eb79.firebaseapp.com',
    databaseURL: 'https://project-9eb79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-9eb79.appspot.com',
    measurementId: 'G-443NDG631N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARNRpHQDBEMcbvX1zNgFiLWEz4o5M6So',
    appId: '1:631796041141:android:07def17b22401868d485fc',
    messagingSenderId: '631796041141',
    projectId: 'project-9eb79',
    databaseURL: 'https://project-9eb79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-9eb79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGEKdSMY3zUQm2mZ4AKd5EO1XT7hyrps',
    appId: '1:631796041141:ios:94d5cb5f30ab807dd485fc',
    messagingSenderId: '631796041141',
    projectId: 'project-9eb79',
    databaseURL: 'https://project-9eb79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-9eb79.appspot.com',
    iosBundleId: 'com.example.plantProject',
  );
}
